name: Build Embedded Projects

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build 01-bare-metal-blink
        run: |
          cd 01-bare-metal-blink
          make clean && make

      - name: Build 02-uart-driver
        run: |
          cd 02-uart-driver
          make clean && make

      - name: Build 03-uart-interrupt
        run: |
          cd 03-uart-interrupt
          make clean && make

      - name: Build 04-multi-sensor-polling
        run: |
          cd 04-multi-sensor-polling
          make clean && make
      
      - name: Build 05-stm32-bare-metal
        run: |
          cd 05-stm32-bare-metal
          make clean && make
      
      - name: Build 06-custom-hal
        run: |
          cd 06-custom-hal
          make clean && make

      - name: Build 07-dma-data-acquisition
        run: |
          cd 07-dma-data-acquisition
          make clean && make

      - name: Build 08-freeRTOS-basics
        run: |
          cd 08-freeRTOS-basics
          make clean && make

      - name: Build 09-inter-task-comm
        run: |
          cd 09-inter-task-comm
          make clean && make